<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Condition=" '$(Configuration)' == 'Release' ">
  </ItemGroup>

  <ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(Configuration)' == 'Debug' ">
		<ProjectReference Include="../../../src/StpSDK.JsonRpc/StpSDK.csproj" />
  </ItemGroup>
	
</Project>
